spring:
  datasource:
    url: jdbc:h2:file:C:\Users\shreyask\Documents\MicroServices\accounts\accounts\accounts\src\main\resources
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
